### ISSUE TITLE
SecretValue in KeyVault & Opening some link!!

### ISSUE THREAD

**Issue by JicenJol** [pravin-raut/IPLAnalysisDatabricks#7]
Hello Brother,

Thanks for the IPL Data Analytics Project.
We are following your YouTube channel & reached at Video. [IPL 2023 Data Analysis Using Databricks Project | 02 Environment Setup](https://www.youtube.com/watch?v=wTnX7soPpfc&list=PLEnhbgHn_gC5aoWKPd49KKYuFH1tw6VaR&index=4)
Can you explain what exactly you mean by **Container Value**? For Container Value we are entering below value in Secret Value.

![BlobValue](https://user-images.githubusercontent.com/128591172/227165869-801dca38-e355-4b4c-a685-a506ab37ab07.png)

What exactly you are trying to do at 7th Minute of video. Some Secret Value entering in Databricks but how? From where you pasted those url when you duplicated the screen. Can you put some light on it.

Enjoying the project, Keep posting wonderful things.

Lots of Love From Russia to India.

**Comment by pravin-raut** [comment]
Hello JicenJol ,

Glad that you are liking it, I can help you with this, should we connect on google meet? I have some time tomorrow on Sunday and I am in London at the moment So 10:00 AM BST will work for me.
